name: downport
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_downpor_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: 702

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - run: npm ci
    - run: npm run prepare_downport
    - run: npm run delete_testclasses
    - run: npm run update_xml_files
    - run: npm run donwpport
    
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        branch: auto-downport
        title: "Auto Downport"
        commit-message: "Auto Downport"
        body: "Automated downport of changes from main"
        labels: "auto-merge"

    - name: Auto merge downport
      run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --squash --auto